# Generated by Django 4.2 on 2024-03-22 11:14

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "text",
                    models.TextField(
                        validators=[catalog.models.perfect_validator],
                        verbose_name="текст",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="слаг"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Слаг"),
                ),
                (
                    "weight",
                    models.IntegerField(
                        blank=True, default=100, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.item"
                    ),
                ),
            ],
        ),
    ]
