# Generated by Django 4.2 on 2024-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_category_items_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(related_name="items", to="catalog.tag"),
        ),
    ]
